[tool.poetry]
name = "essencia_pack"
version = "0.1.1"
description = ""
authors = ["arantesdv <arantesdv@me.com>"]

[tool.poetry.dependencies]
python = "^3.7"
fastapi = "^0.63.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
