[build-system]
requires = ["flit_core >=2,<4"]
build-backend = "flit_core.buildapi"

[tool.flit.metadata]
module = "TimeTaggerRPC"
author = "Igor Shavrin"
author-email = "igor@swabianinstruments.com"
home-page = "http://pypi.python.org/pypi/TimeTaggerRPC/"
description-file = "README.md"
requires = [
    "Pyro5",
    "numpy"
]
requires-python = ">=3.6,<4"
license = "BSD 3-Clause"
classifiers=[
    "Intended Audience :: Developers",
    "License :: OSI Approved :: BSD License",
    "Development Status :: 3 - Alpha",
    "Programming Language :: Python :: 3",
    "Topic :: Software Development :: Libraries :: Python Modules",
    "Topic :: Scientific/Engineering",
]

[tool.flit.metadata.urls]
#Documentation = "https://swabianinstruments.gitlab.io/timetagger-rpc/"
Hardware = "https://www.swabianinstruments.com/time-tagger/"

[tool.flit.scripts]
TimeTaggerRPC-server = "TimeTaggerRPC.server:start_server"

