[build-system]
requires = [ "whey",]
build-backend = "whey"

[project]
name = "mkrecipe"
version = "0.2.0"
description = "A tool to create recipes for building conda packages from distributions on PyPI."
readme = "README.rst"
keywords = [ "pep621", "conda", "packaging", "distribution",]
dynamic = []
dependencies = [
    "click>=7.1.2",
    "consolekit>=1.1.1",
    "dom-toml>=0.3.0",
    "domdf-python-tools>=2.7.0",
    "jinja2>=2.11.3",
    "packaging>=20.9",
    "pyproject-parser>=0.1.1",
    "shippinglabel>=0.13.0",
    "typing-extensions>=3.7.4.3",
    "whey>=0.0.12",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python",
    "Programming Language :: Python :: 3 :: Only",
    "Programming Language :: Python :: 3.6",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: Implementation :: CPython",
    "Programming Language :: Python :: Implementation :: PyPy",
    "Topic :: System :: Archiving :: Packaging",
    "Typing :: Typed",
]
requires-python = ">=3.6"

[[project.authors]]
email = "dominic@davis-foster.co.uk"
name = "Dominic Davis-Foster"


[project.license]
file = "LICENSE"

[project.urls]
Homepage = "https://github.com/repo-helper/mkrecipe"
"Issue Tracker" = "https://github.com/repo-helper/mkrecipe/issues"
"Source Code" = "https://github.com/repo-helper/mkrecipe"
Documentation = "https://mkrecipe.readthedocs.io/en/latest"

[project.scripts]
mkrecipe = "mkrecipe.__main__:main"

[tool.mkrecipe]
conda-channels = [ "conda-forge", "domdfcoding",]
extras = "all"

[tool.whey]
base-classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "Topic :: System :: Archiving :: Packaging",
    "Typing :: Typed",
]
python-versions = [ "3.6", "3.7", "3.8", "3.9",]
python-implementations = [ "CPython", "PyPy",]
platforms = [ "Windows", "macOS", "Linux",]
license-key = "MIT"
additional-files = [ "include mkrecipe/recipe_template.ymlt",]
