[tool.poetry]
name = "amo_partner_crawler"
version = "2.1.2"
description = "SELENIUM CRAWLER FOR SCRAPING BILLING DATA FROM AMOCRM PARTNER CABINET"
authors = ["Igor Romaschenko <rocinantt@gmail.com>"]

[tool.poetry.dependencies]
python = "^3.8"
selenium = "^3.141.0"
pydantic = "^1.8.1"
datedelta = "^1.3"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"
