[tool.poetry]
name = "xawsprofile"
version = "0.1.13"
description = "AWS profile utility"
readme = "README.md"
authors = ["Daniel Clayton <dclayton@godaddy.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = ">=3.6.1"
click = "^7.1.2"

[tool.poetry.dev-dependencies]
pytest = "^5.2"
dephell = "^0.8.3"

[tool.poetry.scripts]
awsprofile = "xawsprofile.cli:main"

[build-system]
requires = ["setuptools", "poetry>=0.12"]
build-backend = "poetry.masonry.api"

