[tool.poetry]
name = "triehard"
version = "0.1.7"
description = "A badly implemented trie"
authors = ["iCalculated <fufa0001@gmail.com>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"
requests = "^2.25.1"
python-nubia = "^0.2b5"
termcolor = "^1.1.0"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.scripts]
trie = 'cli:main'
